apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: time-service
  labels:
    app: time-service
spec:
  template:
    metadata:
      labels:
        app: time-service
        tier: web
    spec:
      containers:
      - name: time-service
        image: vijayjaiswalvictory/time-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: vjcred